module.exports = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Overview of ImmutableX',
      link: { type: 'doc', id: 'overview/start-here' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Key concepts',
      link: { type: 'doc', id: 'key-concepts/overview' },
      items: [
        'key-concepts/anatomy-smart-contract',
        'key-concepts/deep-dive-minting',
        'key-concepts/deep-dive-metadata',
        'key-concepts/deep-dive-royalties',
        'key-concepts/deep-dive-deposits-withdrawals'
      ],
    },
    {
      type: 'category',
      label: 'Launch a collection',
      link: { type: 'doc', id: 'launch-collection/overview/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'launch-collection',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: { type: 'doc', id: 'guides/overview' },
      items: [
        'guides/overview',
        {
          type: 'category',
          label: 'Basic guides',
          link: { type: 'doc', id: 'guides/basic-guides/overview/index' },
          items: [
            'guides/basic-guides/install-initialize/index',
            'guides/basic-guides/get-data/index',
            'guides/basic-guides/generate-signers/index',
            'guides/basic-guides/register-users/index',
            'guides/basic-guides/create-orders/index',
            'guides/basic-guides/create-trades/index',
            'guides/basic-guides/mint-assets/index',
            'guides/basic-guides/transfers/index',
            'guides/basic-guides/deposits-withdrawals/index',
          ]
        },
        {
          type: 'category',
          label: 'Advanced guides',
          items: [
            {
              type: 'autogenerated',
              dirName: 'guides/advanced-guides',
            },
          ],
        },
        {
          type: 'category',
          label: 'Design guides',
          link: { type: 'doc', id: 'guides/design-guides/wallet-sdk-ui-guide' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'guides/design-guides',
            },
          ],
        },
        {
          type: 'category',
          label: 'JS SDK',
          link: { type: 'doc', id: 'guides/js-sdk/index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'guides/js-sdk',
            },
          ],
        },
        {
          type: 'category',
          label: 'Link SDK',
          link: { type: 'doc', id: 'guides/link-sdk/sdk-api' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'guides/link-sdk',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: { type: 'doc', id: 'tutorials/overview' },
      items: [
        'tutorials/zero-to-hero-nft-minting',
      ]
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [
        {
          type: 'autogenerated',
          dirName: 'troubleshooting',
        },
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [
        {
          type: 'autogenerated',
          dirName: 'resources',
        },
      ],
    },
    {
      type: 'doc',
      label: 'Contribute to these docs',
      id: 'contributing'
    },
  ],
  learnSidebar: [
    {
      type: 'category',
      label: 'Learn',
      link: { type: 'doc', id: 'learn/getting-started/overview' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'learn',
        },
      ],
    },
  ]
};
